import { darken, lighten, toRgba } from "color2k"

import {
  ColorwayConfig,
  ColorwayFoundations,
  FoundationConfig,
  SurfaceColorwayConfig,
} from "./utils"
import { pallet } from "./utils/color-pallet"

export const makeShades = (
  color: string,
  shades: FoundationConfig<number>
): FoundationConfig => ({
  "00": toRgba(darken(color, shades["00"])),
  "01": toRgba(darken(color, shades["01"])),
  "02": toRgba(darken(color, shades["02"])),
  "03": toRgba(darken(color, shades["03"])),
  "04": toRgba(darken(color, shades["04"])),
  "05": toRgba(color),
  "06": toRgba(lighten(color, shades["06"])),
  "07": toRgba(lighten(color, shades["07"])),
  "08": toRgba(lighten(color, shades["08"])),
  "09": toRgba(lighten(color, shades["09"])),
  "10": toRgba(lighten(color, shades["10"])),
})
export const makeColorwayFoundations = ({
  colors: { black, white, ...c },
  shades,
}: ColorwayConfig): ColorwayFoundations => ({
  brand1: makeShades(c.brand1, shades),
  brand2: makeShades(c.brand2, shades),
  brand3: makeShades(c.brand3, shades),
  neutral: makeShades(c.neutral, shades),
  inverse: makeShades(c.inverse, shades),
  info: makeShades(c.info, shades),
  success: makeShades(c.success, shades),
  warning: makeShades(c.warning, shades),
  danger: makeShades(c.danger, shades),
  enabled: makeShades(c.enabled, shades),
  disabled: makeShades(c.disabled, shades),
  error: makeShades(c.error, shades),
  selected: makeShades(c.selected, shades),
  black,
  white,
  colorways: {
    background: {
      backgroundColor: ["enabled", "05"],
      borderColor: ["enabled", "04"],
      textDecorationColor: "currentColor",
      color: "readable",
      fill: "currentColor",
      stroke: "currentColor",
    },
    inverse: {
      backgroundColor: ["inverse", "05"],
      borderColor: ["inverse", "04"],
      textDecorationColor: "currentColor",
      color: "readable",
      fill: "currentColor",
      stroke: "currentColor",
    },
    enabled: {
      backgroundColor: ["enabled", "05"],
      borderColor: ["enabled", "04"],
      textDecorationColor: "currentColor",
      color: "readable",
      fill: "currentColor",
      stroke: "currentColor",
    },
    hover: {
      backgroundColor: ["enabled", "04"],
      borderColor: ["enabled", "03"],
      textDecorationColor: "currentColor",
      color: "readable",
      fill: "currentColor",
      stroke: "currentColor",
    },
    active: {
      backgroundColor: ["enabled", "03"],
      borderColor: ["enabled", "02"],
      textDecorationColor: "currentColor",
      color: "readable",
      fill: "currentColor",
      stroke: "currentColor",
    },
    disabled: {
      backgroundColor: ["disabled", "05"],
      borderColor: ["disabled", "04"],
      textDecorationColor: ["disabled", "02"],
      color: ["disabled", "02"],
      fill: ["disabled", "02"],
      stroke: ["disabled", "02"],
    },
    error: {
      backgroundColor: ["enabled", "05"],
      borderColor: ["error", "05"],
      textDecorationColor: "currentColor",
      color: "readable",
      fill: ["error", "05"],
      stroke: ["error", "05"],
    },
  },
})
export const defaultConfig: ColorwayConfig = {
  colors: {
    brand1: pallet.orangePeel,
    brand2: pallet.violet,
    brand3: pallet.aquamarine,
    neutral: pallet.gray10,
    inverse: pallet.gray90,
    info: pallet.capri,
    success: pallet.emerald,
    warning: pallet.goldenYellow,
    danger: pallet.crimson,
    enabled: pallet.gray10,
    disabled: pallet.gray50,
    error: pallet.crimson,
    selected: pallet.violet,
    black: "#030303",
    white: "#fdfdfd",
  },
  shades: {
    "00": 0.85,
    "01": 0.75,
    "02": 0.5,
    "03": 0.25,
    "04": 0.25,
    "05": 0,
    "06": 0.25,
    "07": 0.25,
    "08": 0.5,
    "09": 0.75,
    "10": 0.85,
  },
}
