version: "3"

services:

  app:
    image: horns:latest
    command: yarn develop --protocol=http --host=0.0.0.0 --port=8000
    volumes:
    - ./:/app
    working_dir: /app
    ports:
    - "80:8000"
    environment:
      VIRTUAL_HOST: horns.local
