version: "3"

services:

  app:
    image: kedge-ui:latest
    command: yarn docker-docz
    volumes:
    - ./:/site
    working_dir: /site
    ports:
    - "8000:8000"
    environment:
      VIRTUAL_HOST: ui.kedge.local
