version: "3"

services:

  app:
    image: horns:latest
    command: yarn develop:docker
    volumes:
    - ./:/site
    working_dir: /site
    ports:
    - "8000:8000"
    environment:
      VIRTUAL_HOST: horns.local
