version: "3"

services:

  ui-dev:
    command: yarn docker-docz
    build: .
    volumes:
    - ./:/site
    working_dir: /site
    ports:
    - "8000:80"
    environment:
      VIRTUAL_HOST: ui.kedge.local

  ui-test:
    command: yarn test:watch
    build: .
    volumes:
    - ./:/site
    working_dir: /site
