version: "3"

services:

  ui-dev:
    command: yarn docker-docz
    build: .
    volumes:
    - ./:/site
    working_dir: /site
    ports:
    - "80:80"
    environment:
      VIRTUAL_HOST: ui.kedge.local

  ui-test:
    command: yarn test
    build: .
    volumes:
    - ./:/site
    working_dir: /site
