import { TypographyConfig } from "./utils"

export const defaultConfig: TypographyConfig = {
  typefaces: {
    primary: {
      fontFamily: "'IBM Plex Sans', Arial, sans-serif",
      fontStyle: "normal",
      fontWeight: 400,
      fontKerning: "auto",
      wordSpacing: "normal",
      textTransform: "none",
      imports: [
        "@fontsource/ibm-plex-sans/300.css",
        "@fontsource/ibm-plex-sans/400.css",
        "@fontsource/ibm-plex-sans/500.css",
        "@fontsource/ibm-plex-sans/600.css",
        "@fontsource/ibm-plex-sans/700.css",
      ],
    },
    secondary: {
      fontFamily: "'IBM Plex Serif', Georgia, sans-serif",
      fontStyle: "normal",
      fontWeight: 400,
      fontKerning: "auto",
      wordSpacing: "normal",
      textTransform: "none",
      imports: [
        "@fontsource/ibm-plex-serif/300.css",
        "@fontsource/ibm-plex-serif/400.css",
        "@fontsource/ibm-plex-serif/500.css",
        "@fontsource/ibm-plex-serif/600.css",
        "@fontsource/ibm-plex-serif/700.css",
      ],
    },
    tertiary: {
      fontFamily: "'JetBrains Mono Variable', 'Courier New', monospace",
      fontStyle: "normal",
      fontWeight: 400,
      fontKerning: "auto",
      wordSpacing: "normal",
      textTransform: "none",
      imports: ["@fontsource/ibm-plex-sans/400.css"],
    },
  },
  sizes: {
    "00": {
      fontSize: "10px",
      lineHeight: "12px",
    },
    "01": {
      fontSize: "12px",
      lineHeight: "16px",
    },
    "02": {
      fontSize: "14px",
      lineHeight: "20px",
    },
    "03": {
      fontSize: "16px",
      lineHeight: "24px",
    },
    "04": {
      fontSize: "18px",
      lineHeight: "28px",
    },
    "05": {
      fontSize: "20px",
      lineHeight: "32px",
    },
    "06": {
      fontSize: "22px",
      lineHeight: "36px",
    },
    "07": {
      fontSize: "24px",
      lineHeight: "40px",
    },
    "08": {
      fontSize: "32px",
      lineHeight: "48px",
    },
    "09": {
      fontSize: "40px",
      lineHeight: "60px",
    },
    "10": {
      fontSize: "52px",
      lineHeight: "64px",
    },
  },
  fonts: {
    display: {
      fontFamily: "secondary",
      fontStyle: "normal",
      fontWeight: "600",
      size: "10",
      textAlign: "start",
      textTransform: "none",
      fontKerning: "auto",
      textIndent: "0",
      wordSpacing: "normal",
      marginTop: "0.5em",
      marginBottom: "1em",
    },
    h1: {
      fontFamily: "secondary",
      fontStyle: "normal",
      fontWeight: "600",
      size: "09",
      textAlign: "start",
      textTransform: "none",
      fontKerning: "auto",
      textIndent: "0",
      wordSpacing: "normal",
      marginTop: "0.5em",
      marginBottom: "1em",
    },
    h2: {
      fontFamily: "secondary",
      fontStyle: "normal",
      fontWeight: "600",
      size: "08",
      textAlign: "start",
      textTransform: "none",
      fontKerning: "auto",
      textIndent: "0",
      wordSpacing: "normal",
      marginTop: "0.5em",
      marginBottom: "1em",
    },
    h3: {
      fontFamily: "secondary",
      fontStyle: "normal",
      fontWeight: "600",
      size: "07",
      textAlign: "start",
      textTransform: "none",
      fontKerning: "auto",
      textIndent: "0",
      wordSpacing: "normal",
      marginTop: "0.5em",
      marginBottom: "1em",
    },
    h4: {
      fontFamily: "primary",
      fontStyle: "normal",
      fontWeight: "600",
      size: "06",
      textAlign: "start",
      textTransform: "none",
      fontKerning: "auto",
      textIndent: "0",
      wordSpacing: "normal",
      marginTop: "0.5em",
      marginBottom: "1em",
    },
    h5: {
      fontFamily: "primary",
      fontStyle: "normal",
      fontWeight: "600",
      size: "05",
      textAlign: "start",
      textTransform: "none",
      fontKerning: "auto",
      textIndent: "0",
      wordSpacing: "normal",
      marginTop: "0.5em",
      marginBottom: "1em",
    },
    h6: {
      fontFamily: "primary",
      fontStyle: "normal",
      fontWeight: "600",
      size: "04",
      textAlign: "start",
      textTransform: "none",
      fontKerning: "auto",
      textIndent: "0",
      wordSpacing: "normal",
      marginTop: "0.5em",
      marginBottom: "1em",
    },
    body1: {
      fontFamily: "primary",
      fontStyle: "normal",
      fontWeight: "400",
      size: {
        sm: "02",
        md: "03",
        lg: "04",
      },
      textAlign: "start",
      textTransform: "none",
      fontKerning: "auto",
      textIndent: "0",
      wordSpacing: "normal",
    },
    body2: {
      fontFamily: "secondary",
      fontStyle: "normal",
      fontWeight: "400",
      size: {
        sm: "02",
        md: "03",
        lg: "04",
      },
      textAlign: "start",
      textTransform: "none",
      fontKerning: "auto",
      textIndent: "0",
      wordSpacing: "normal",
    },
    body3: {
      fontFamily: "tertiary",
      fontStyle: "normal",
      fontWeight: "400",
      size: {
        sm: "02",
        md: "03",
        lg: "04",
      },
      textAlign: "start",
      textTransform: "none",
      fontKerning: "auto",
      textIndent: "0",
      wordSpacing: "normal",
    },
    label: {
      fontFamily: "primary",
      fontStyle: "normal",
      fontWeight: "600",
      size: {
        sm: "02",
        md: "03",
        lg: "04",
      },
      textAlign: "start",
      textTransform: "none",
      fontKerning: "auto",
      textIndent: "0",
      wordSpacing: "normal",
    },
    caption: {
      fontFamily: "primary",
      fontStyle: "normal",
      fontWeight: "400",
      size: {
        sm: "00",
        md: "01",
        lg: "02",
      },
      textAlign: "start",
      textTransform: "none",
      fontKerning: "auto",
      textIndent: "0",
      wordSpacing: "normal",
    },
    captionHeading: {
      fontFamily: "primary",
      fontStyle: "normal",
      fontWeight: "600",
      size: {
        sm: "00",
        md: "01",
        lg: "02",
      },
      textAlign: "start",
      textTransform: "none",
      fontKerning: "auto",
      textIndent: "0",
      wordSpacing: "normal",
    },
  },
}
