export enum OLType {
  a = 'lower-latin',
  A = 'upper-latin',
  i = 'lower-roman',
  I = 'upper-roman',
  Armenian = 'armenian',
  CJKIdeographic = 'cjk-ideographic',
  Decimal = 'decimal',
  DecimalLeadingZero = 'decimal-leading-zero',
  Georgian = 'georgian',
  Hebrew = 'hebrew',
  Hiragana = 'hiragana',
  HiraganaIroha = 'hiragana-iroha',
  Katakana = 'katakana',
  KatakanaIroha = 'katakana-iroha',
  LowerAlpha = 'lower-alpha',
  LowerGreek = 'lower-greek',
  LowerLatin = 'lower-latin',
  LowerRoman = 'lower-roman',
  UpperAlpha = 'upper-alpha',
  UpperGreek = 'upper-greek',
  UpperLatin = 'upper-latin',
  UpperRoman = 'upper-roman',
  None = 'none',
}

export enum ULType {
  Disc = 'disc',
  Circle = 'circle',
  Square = 'square',
  None = 'none',
}
