import Color from 'color'
import { safeGetValue } from './utils'

export const palletColors = [
  'background',
  'background:primary',
  'background:secondary',
  'background:tertiary',
  'background:active',
  'background:inactive',
  'copy',
  'copy:primary',
  'copy:dark',
  'copy:light',
  'primary',
  'secondary',
  'tertiary',
  'light',
  'neutral',
  'dark',
  'success',
  'info',
  'warning',
  'danger',
  'prominent',
]

export const modeColorShades = [
  'background',
  'background-darker',
  'background-dark',
  'background-light',
  'background-lighter',
  'background:primary',
  'background:primary-darker',
  'background:primary-dark',
  'background:primary-light',
  'background:primary-lighter',
  'background:secondary',
  'background:secondary-darker',
  'background:secondary-dark',
  'background:secondary-light',
  'background:secondary-lighter',
  'background:tertiary',
  'background:tertiary-darker',
  'background:tertiary-dark',
  'background:tertiary-light',
  'background:tertiary-lighter',
  'background:active',
  'background:active-darker',
  'background:active-dark',
  'background:active-light',
  'background:active-lighter',
  'background:inactive',
  'background:inactive-darker',
  'background:inactive-dark',
  'background:inactive-light',
  'background:inactive-lighter',
  'copy',
  'copy-darker',
  'copy-dark',
  'copy-light',
  'copy-lighter',
  'copy:primary',
  'copy:primary-darker',
  'copy:primary-dark',
  'copy:primary-light',
  'copy:primary-lighter',
  'copy:dark',
  'copy:dark-darker',
  'copy:dark-dark',
  'copy:dark-light',
  'copy:dark-lighter',
  'copy:light',
  'copy:light-darker',
  'copy:light-dark',
  'copy:light-light',
  'copy:light-lighter',
]

export const palletColorShades = [
  ...modeColorShades,
  '',
  'primary',
  'primary-darker',
  'primary-dark',
  'primary-light',
  'primary-lighter',
  'secondary',
  'secondary-darker',
  'secondary-dark',
  'secondary-light',
  'secondary-lighter',
  'tertiary',
  'tertiary-darker',
  'tertiary-dark',
  'tertiary-light',
  'tertiary-lighter',
  'light',
  'light-darker',
  'light-dark',
  'light-light',
  'light-lighter',
  'neutral',
  'neutral-darker',
  'neutral-dark',
  'neutral-light',
  'neutral-lighter',
  'dark',
  'dark-darker',
  'dark-dark',
  'dark-light',
  'dark-lighter',
  'success',
  'success-darker',
  'success-dark',
  'success-light',
  'success-lighter',
  'info',
  'info-darker',
  'info-dark',
  'info-light',
  'info-lighter',
  'warning',
  'warning-darker',
  'warning-dark',
  'warning-light',
  'warning-lighter',
  'danger',
  'danger-darker',
  'danger-dark',
  'danger-light',
  'danger-lighter',
  'prominent',
  'prominent-darker',
  'prominent-dark',
  'prominent-light',
  'prominent-lighter',
]

export const colorShades = ['darker', 'dark', 'base', 'light', 'lighter']

const basePallet = {
  primary: '#FFAA00',
  secondary: '#3914AF',
  tertiary: '#009999',
  violet: '#7f00ff',
  indigo: '#3f00ff',
  blue: '#1a99ff',
  green: '#00aa33',
  yellow: '#f6d500',
  orange: '#ff9900',
  red: '#ff3600',
  white: '#ffffff',
  gray: '#888888',
  black: '#010101',
}

const defaultPallet = {
  primary: basePallet.primary,
  secondary: basePallet.secondary,
  tertiary: basePallet.tertiary,
  light: basePallet.white,
  neutral: basePallet.gray,
  dark: basePallet.black,
  success: basePallet.green,
  info: basePallet.blue,
  warning: basePallet.orange,
  danger: basePallet.red,
  prominent: basePallet.primary,
  hover: basePallet.secondary,
  active: basePallet.tertiary,
  disabled: basePallet.gray,
}

class ColorPallet {
  constructor(config = {}) {
    palletColors.forEach(color => {
      const value = safeGetValue(config, color, defaultPallet[color])
      this[color] = Color(value)
    })
    const hValue = safeGetValue(config, 'hover', defaultPallet.hover)
    this.hover = Color(hValue)
    const aValue = safeGetValue(config, 'active', defaultPallet.active)
    this.active = Color(aValue)
  }
}

export default ColorPallet
