/* eslint-disable import/prefer-default-export */

export const safeGetValue = (config, key, defaultValue) => {
  return typeof config[key] === 'undefined' ? defaultValue : config[key]
}

export const palletColors = [
  'primary',
  'secondary',
  'tertiary',
  'light',
  'neutral',
  'dark',
  'success',
  'info',
  'warning',
  'danger',
]

export const palletColorShades = [
  '',
  'primary',
  'primary-darker',
  'primary-dark',
  'primary-light',
  'primary-lighter',
  'secondary',
  'secondary-darker',
  'secondary-dark',
  'secondary-light',
  'secondary-lighter',
  'tertiary',
  'tertiary-darker',
  'tertiary-dark',
  'tertiary-light',
  'tertiary-lighter',
  'light',
  'light-darker',
  'light-dark',
  'light-light',
  'light-lighter',
  'neutral',
  'neutral-darker',
  'neutral-dark',
  'neutral-light',
  'neutral-lighter',
  'dark',
  'dark-darker',
  'dark-dark',
  'dark-light',
  'dark-lighter',
  'success',
  'success-darker',
  'success-dark',
  'success-light',
  'success-lighter',
  'info',
  'info-darker',
  'info-dark',
  'info-light',
  'info-lighter',
  'warning',
  'warning-darker',
  'warning-dark',
  'warning-light',
  'warning-lighter',
  'danger',
  'danger-darker',
  'danger-dark',
  'danger-light',
  'danger-lighter',
]

export const colorShades = ['darker', 'dark', 'base', 'light', 'lighter']
